### ISSUE TITLE
wired ethernet required for bootstrap?

### ISSUE THREAD

**Issue by qwrrty** [HelmSecure/armbian-images#11]
Step 3 of the installation instructions say "Connect your Helm to power and to your router via ethernet". Is it really required to have the Helm connected via Ethernet for the bootstrap process, or can it be bootstrapped over USB and then updated directly via wifi?

**Comment by l3nticular** [comment]
I believe I saw in another thread that it’s so you can use the Ethernet lights as indication when it has successfully hard powered off (the 25s hold). When in mask rom mode you should see no Ethernet lights on I believe.

**Comment by l3nticular** [comment]
Also you’ll need Ethernet once you flash the device to log in, but I don’t believe it should be required until that step.

**Comment by qwrrty** [comment]
OK, so real wired Ethernet is definitely required to complete the installation process before the device is usable over wifi -- that's basically what I really was trying to ask. Thank you!

**Comment by l3nticular** [comment]
There’s probably some way around it but wired Ethernet is going to be easiest by far.

**Comment by l3nticular** [comment]
It seemed the easiest way to get Wifi going once you’re logged in is ‘apt install armbian-config’ then ‘armbian-config’.

**Comment by dsigurds** [comment]
Yes, wired ethernet is just required for initial setup.  Once you've created your username and password and configured wifi you can unplug from ethernet if you wish.  Although, we've always recommended that people use ethernet over wifi.
