### ISSUE TITLE
Flashed it and now the thing is a brick

### ISSUE THREAD

**Issue by jimminycreeket** [HelmSecure/armbian-images#16]
I successfully flashed my 2a version according to the instructions, but now it won't power on.

**Comment by l3nticular** [comment]
I don’t believe the front light comes on under Armbian even when it’s working. Check the Ethernet lights.

Should be able to repeat the procedure whenever you want.  The point of the mask rom bootloader is so that it won’t brick regardless of how corrupt the eMMC and NVMe might be.

**Comment by l3nticular** [comment]
Confirmed that even with it up and running, the front light is not on.  You should always be able to get it into mask ROM recovery mode by holding the button while it powers up.  I believe the 25s hold is to ensure that the unit is completely powered down, including not running on battery power.

**Comment by jimminycreeket** [comment]
Thanks @l3nticular
