### ISSUE TITLE
Armbian first login via SSH - Connection refused

### ISSUE THREAD

**Issue by anthonysexton** [HelmSecure/armbian-images#20]
After successfully flashing the device and rebooting it, when trying to log in via SSH on port 22, the response is 'Connection Refused'.

Restarting the device also doesn't seem to fix this.

**Comment by anthonysexton** [comment]
Looks like the issue was due to the restart. Connecting via SSH after the 'Reset Device' command is the way to go.

**Comment by wi-gett** [comment]
Thanks. This helped!
