### ISSUE TITLE
Now that helm the company has shut down

### ISSUE THREAD

**Issue by ivahos** [HelmSecure/armbian-images#21]
I have not seen any messages from the helm team here since late December. Are you guys still around or is these images now set adrift?

**Comment by bimmerr2019** [comment]
I ordered a helm2 on 1/15. Big mistake. The website took the money but no one is shipping it.

**Comment by jglover512** [comment]
I am still here. poking at my helm when i can to see what i want to end up doing with it. leading contender is a Home Assistant server. i am also looking at starting a subreddit to keep chatting about these boxes and what we can do with them. anyone interested?

**Comment by l3nticular** [comment]
I’m in for a subreddit or whatever.  I have 10 or so services running on my Pi4; planning on moving the heaviest services (probably photoprism) onto it, and maybe evaluating frigate on it.

**Comment by jglover512** [comment]
for those that are interested.   r/HelmServerMods

**Comment by dsigurds** [comment]
> I ordered a helm2 on 1/15. Big mistake. The website took the money but no one is shipping it.

We are super low on 1TB units that remain and so sorry for the delay.  We'll be shipping you out that device next week.

**Comment by optionman2018** [comment]
> > I ordered a helm2 on 1/15. Big mistake. The website took the money but no one is shipping it.
> 
> We are super low on 1TB units that remain and so sorry for the delay. We'll be shipping you out that device next week.

that's awesome news! thanks Dirk!!

**Comment by dsigurds** [comment]
I plan to continue to support this project on the side for the foreseeable future.  But, updates may be relatively slow.
