### ISSUE TITLE
Updated kernel?

### ISSUE THREAD

**Issue by krioso** [HelmSecure/armbian-images#22]
As the 4.4 kernel is past end-of-life - can we get an update on any plans for updating the kernel?

Thanks.

**Comment by krioso** [comment]
I'll put my hopes on the following response to a different issue re: Armbian disk IO.

https://github.com/HelmSecure/armbian-images/issues/10#issuecomment-1424572655

**Comment by krioso** [comment]
It appears that the #10 comment was potentially resolved but uses the same kernel.

Is there a reason why the 4.4 kernel is being used? Is there or will there be a way to use a newer kernel? The 4.4. kernel is past end of life.

**Comment by dsigurds** [comment]
The 4.4 kernel is what was supported by Rockchip.  I think what we'll do is create a repo with the Armbian build configuration which should allow others to contribute in upgrading the kernel.

**Comment by dsigurds** [comment]
Closing as this duplicated issue #28
