### ISSUE TITLE
Loaded Armbian but only recognizes 7.3GB ssd drive size instead of 1TB

### ISSUE THREAD

**Issue by git529** [HelmSecure/armbian-images#33]
Is there something that needs to be done in order for it to recognize the full 1TB size?

![image](https://github.com/HelmSecure/armbian-images/assets/85685642/d263e258-b0f8-4494-8ea6-5b96c26cdfb9)

![image](https://github.com/HelmSecure/armbian-images/assets/85685642/2f8ae792-4eba-441b-bb5b-bc5b77b063d1)

**Comment by git529** [comment]
closed

**Comment by justinhamlett** [comment]
was there a fix to this?

**Comment by l3nticular** [comment]
There’s an encrypted LVM volume(s) on the NVMe.  I never tried to access those volumes, but I did wipe and set up a new one and use it for my docker containers and data.

https://old.reddit.com/r/HelmServerMods/comments/10pfcdf/setting_up_ssd/

**Comment by justinhamlett** [comment]
Thank you for the response and information! Worked like a charm and now have access to a 953G data volume.

So the helmv2 has 2 separate storage disks, one disk for booting/OS at /dev/mmcblk2 (7.28G) and a NVMe disk at /dev/nvme0n1 (953.87G) for storing data?

**Comment by l3nticular** [comment]
Yes there is an eMMC (basically the chip from a microsd card) soldered onto the board, and the NVMe disk is just a standard M.2 SSD that you can remove and use in another device if you want.
