### ISSUE TITLE
Difficulty to get into Armbian flash mode

### ISSUE THREAD

**Issue by krioso** [HelmSecure/armbian-images#4]
I have followed these directions a dozen times or more. Can you add more detail as to what I am doing wrong. For example:

- After the 25 seconds - do I release the button, or keep holding it in and just unplug and then plug in power?
- Do the 25 second and 6 second times need to be precise?
- Do you need to wait for some amount of time between the 25 second event and the 6 second event, or can you do it immediately?
- Does the Helm server shut down by itself after the 25 second event? What state should the power light be in after the 25 second event but before the 6 second event?

On many of my attempts the power will not come back on (or at least the light is not on) and I need to let it sit for a while and then come back and play around with power / no power before it comes back online in normal Helm mode.

=======================================

5. Remove the power cable, press the power button and hold, insert power cable. Keep the power button pressed for 6 seconds after inserting power and then release. This process will put your Helm into maskrom mode.

**Comment by dsigurds** [comment]
After the 25 second press you release the button.  The 25 second press will work for any duration over 20 seconds.  The 6 second press in reality is between 5-10 seconds.  So, no it doesn't need to be precise.  You don't need to wait.  After the 25 second press remove the power cable, press and hold the button, and then plug back in power with the button pressed.  The important thing is that the button must be pressed and held while you insert the power cable.

**Comment by krioso** [comment]
Thanks so much for the quick reply. After the 25+ second event, and after immediately unplugging the power, doing the 5-10 second event (holding the button and then plugging the power cable back in) - should the power light then be on after the second event? My unit appears to be turned off as far as the power light is concerned. the lsusb command does not show the additional USB device either.

**Comment by krioso** [comment]
In case it matters - this is a Helm V2a.

**Comment by krioso** [comment]
Still having issues....maybe a short YouTube video could be posted to demo it?

At the moment, I cannot get the unit powered on back to standard Helm operation. Will let it sit for a while unplugged, that has worked so far to get it back to normal mode. No indication of any success in getting to flash-ready mode.

**Comment by dsigurds** [comment]
I'll post a video when I have the chance.  Just for clarification, the button must be held down before you apply power and then must remain held down for 6 seconds after the power is applied.  After the 6 seconds release the button and that should put it into maskrom mode.

**Comment by krioso** [comment]
Here are the exact steps I followed:

- Attach power cable and Ethernet to the Helm.
- Wait for the Helm to register as Online in the Helm app.
- Hold the button for 25 seconds.
- Release the button
- Pull the power cable out
- Hold the power button in while I re-attach the power cable
- Continue to hold the power button in for 6 seconds (also tried 5-10 seconds)
- Attach the USB cable from my Linux host to one of the USB-C ports to the right of the Ethernet port on the Helm when looking at it from the rear
- I observe that the Helm power light is not on at this point
- No new USB device shows up on the Linux host when I issue the lsusb command on the Linux host.

What usually occurs is that the Helm power light is not on for the second event and the server does not show in the lsusb list on my Linux host.

Then I have difficulty getting it to power back on in standard mode. On my last attempt I let the unit sit disconnected from power and network for some hours and then plugged it in. At this moment the Hem is online in normal mode with the Helm app indicating that the Helm is online.

I checked the Linux host for USB "reception" by attaching and detaching other devices to the USB port and they appear and disappear from the lsusb list. So the Linux host will register a new USB device once attached.

My earlier question also remains: Should the Helm power light be on after executing the 6 second event? 

Thanks again.

**Comment by krioso** [comment]
I am trying it again today. I just did the 25 second press (I held it for 30), released the power button, unplugged the power cable, held the button in, plugged the power cable in and held the button for 9 seconds.The good news is that the power light is on even after the second 6+ (9) second event. So far though, no sign of recognizing the USB on the linux host. WIll keep playing with it.

**Comment by krioso** [comment]
The power light remained on because the Helm is still registering as Online. I tried again, this time I pulled the power cable *while* I was still holding in the button for the 25+ second event - then I did the 6-second event. The power light is off but the Rockchip USB device is now showing on the lsusb list on the Linux host.

It seems as thought pulling the power cable for the first 25+ second event while continuing to hold the putton in while removing the pwoer cable may have been the trick. Now to see if I can successfully flash the Armbian image. with rkdeveloptool.

**Comment by krioso** [comment]
Flashing went well without any issues. Got a notification from my router that a new network device has joined the network ("helm-v2a"). Now on to the "setting up Armbian for ssh" steps.

In the instructions I prefaced the rkdeveloptool execution with ./ as follows to avoid "command not found":

$ sudo ./rkdeveloptool db helm-loader-build-38.bin
$ sudo ./rkdeveloptool wl 0 [the .img file downloaded from here]
$ sudo ./rkdeveloptool ul helm-loader-build-38.bin
$ sudo ./rkdeveloptool rd

**Comment by dsigurds** [comment]
Thanks for your persistence and I'm happy that you got it up and running.

**Comment by git529** [comment]
> The power light remained on because the Helm is still registering as Online. I tried again, this time I pulled the power cable _while_ I was still holding in the button for the 25+ second event - then I did the 6-second event. The power light is off but the Rockchip USB device is now showing on the lsusb list on the Linux host.
> 
> It seems as thought pulling the power cable for the first 25+ second event and continuing to hold the putton in while removing the power cable may have been the trick. Now to see if I can successfully flash the Armbian image. with rkdeveloptool.

Hi. Can you list the steps necessary to format/mount the nvme drive?

**Comment by l3nticular** [comment]
@git529 you can follow these steps:
https://reddit.com/r/HelmServerMods/comments/10pfcdf/setting_up_ssd/

**Comment by git529** [comment]
> @git529 you can follow these steps: https://reddit.com/r/HelmServerMods/comments/10pfcdf/setting_up_ssd/

Thank you! I followed the steps and I have now permanently mounted the 1TB ssd in /mnt/helm-data and I can see it doing 'df -H'

However, I was hoping to do a normal install where everything is installed on the ssd drive so that the standard folders (/etc /home /media /opt /var) are automatically using the ssd space. Is that possible? How could that be achieved?

**Comment by l3nticular** [comment]
At this point, you’re now asking standard Linux questions so there are many resources.

The short answer is that I don’t know exactly.  If you just want to move those directories, it should be not too bad. It might be as simple as creating new virtual volumes, mounting them t a temporal location, copying the existing files, then setting them to the desired mount locations in fatal and rebooting.

 If you want to move the whole root partition, then you’d need the boot partition to support LVM, which I’ve done on raspberry pi but I think that has a different bootloader.

My personal opinion is that I really just want a few brand new volumes (docker, data, etc.) and don’t need the base OS to be on LVM, so I didn’t bother. You could also just put individual users’ home directories each on their logical volumes.

**Comment by l3nticular** [comment]
One similar option if you’re looking to move the root:

https://forum.radxa.com/t/configured-armbian-move-to-nvme/2585/9

> boot from eMMC, root from NVME.
> To do this, create the root partition on your NVME drive, using gparted for example.
> 
> After that run the following command from Armbian:
> sudo armbian-config
> 
> and choose option to move / install to NVME partition.

You might not want to use LVM with this option though (I’m not sure if the bootloader or the eMMC boot partition supports it).  But I love LVM for backups since you can snapshot and then transfer the snapshots.
