### ISSUE TITLE
Lost at Step 2

### ISSUE THREAD

**Issue by btodd0013** [HelmSecure/armbian-images#7]
I get confused at this point can someone tell me how to get to root.  ive tried CD: rkdeveloptool i get an error.

2 go into root of rkdeveloptool
3.aclocal
4.autoreconf -i
5.autoheader
5.automake --add-missing
4 ./configure
5 make

**Comment by btodd0013** [comment]
rkdeveloptool
/snap/rkdeveloptool/7/snap/command-chain/snapcraft-runner: 5: exec: /snap/rkdeveloptool/7/usr/bin/rkdeveloptool: Exec format error

**Comment by mongobit** [comment]
i appear to be stuck at the same step setting up my host linux system. fresh kubuntu install. output of the make command here:

ake[1]: Entering directory '/home/REDACTED/Downloads/rkdeveloptool-master'
g++ -DHAVE_CONFIG_H -I. -I./cfg  -Wall -Werror -Wextra -Wreturn-type -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -I/usr/include/libusb-1.0   -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp
main.cpp: In function ‘bool _Z9mergeBootv.part.0()’:
main.cpp:1493:43: error: ‘%s’ directive output may be truncated writing up to 557 bytes into a region of size 5 [-Werror=format-truncation=]
 1493 |         snprintf(buffer, sizeof(buffer), "%s", chip);
      |                                           ^~
......
 1534 |                 chipType = convertChipType(chip + 2);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:894,
                 from DefineHeader.h:3,
                 from main.cpp:11:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:35: note: ‘__builtin_snprintf’ output between 1 and 558 bytes into a destination of size 5
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:491: main.o] Error 1
make[1]: Leaving directory '/home/REDACTED/Downloads/rkdeveloptool-master'
make: *** [Makefile:511: all-recursive] Error 1

**Comment by stealthcypher** [comment]
@btodd0013 

The more verbose steps to install rkdeveloptool require you to git clone the repo.  So depending on the OS you are using and where you want to clone the repo to, the general steps are:

```
Sudo apt-get Install libudev-dev libusb-1.0.0-dev dh-autoreconf
Sudo apt-get install pkg-config libusb-1.0
cd ~/Downloads/
mkdir rkdeveloptool
git clone https://github.com/rockchip-linux/rkdeveloptool rkdeveloptool
cd rkdeveloptool
autoreconf -i
./configure
make
sudo cp rkdeveloptool /usr/local/bin/
```

@mongobit There is a main.cpp file in the rkdirectory.  There is a variable currently limited to 5 bites that needs 558.  For me I had to edit the section at line 1491 and update the variable from 5 to 558 referenced from this [rkdeveloptool Issue Comment](https://github.com/rockchip-linux/rkdeveloptool/issues/55#issuecomment-922459059)

```
cd rkdeveloptool
vi main.cpp 
1491G
- and change size from 5 to 558
```

**Comment by mongobit** [comment]
done. my helm is converted to Armbian. now to decide what i want to use it for.

**Comment by stealthcypher** [comment]
Hi @mongobit , mind if I ask how long it took to flash the Armbian image?  I've been sitting at the wl command for a couple hours I think.

**Comment by mongobit** [comment]
a few minutes. i had issues getting rkdevelop to actually install but once i googled my way through the errors it took less than 10 minutes till i was logging in and doing the update.

**Comment by mongobit** [comment]
are you sure you are using the right image? i have a helm from the first batch and it worked just fine for me.

**Comment by stealthcypher** [comment]
Ah yep, my command never went through, just went through all the steps again and noticed the percentage.  I am all installed!

**Comment by mongobit** [comment]
congrats. i am now poking around seeing what i can do with this box. trying to get the remote desktop package working. might turn it into a Kalbian box.

**Comment by ronnie-coleman2** [comment]
I'm really stuck here. I followed the more detailed steps from @stealthcypher but not getting past the autoreconf -i steps. What I get in return:

configure.ac:8: warning: 'AM_CONFIG_HEADER': this macro is obsolete.
configure.ac:8: You should use the 'AC_CONFIG_HEADERS' macro instead.
./lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
aclocal.m4:1021: AM_CONFIG_HEADER is expanded from...
configure.ac:8: the top level

**Comment by l3nticular** [comment]
@ronnie-coleman2 you're going to have to post more of the output. Those are warnings not showing a failure.

**Comment by ronnie-coleman2** [comment]
@l3nticular When I run the next step for ./configure I get this output:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking for clang++... no
checking whether the compiler supports GNU C++... no
checking whether g++ accepts -g... no
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... none
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/home/reckless/Downloads/rkdeveloptool/rkdeveloptool':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details

**Comment by dsigurds** [comment]
@ronnie-coleman2 have you been able to resolve your issue with compiling rkdeveloptool?  If not, post the content of the config.log file.
